<a href="https://colab.research.google.com/github/OlhaYastrebova/goit-ds-hw/blob/main/Hw4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install numpy


In [2]:
import numpy as np



In [3]:
import numpy as np

# Створення одновимірного масиву з першими 10-ма натуральними числами
vector = np.arange(1, 11)

# Виведення значення масиву
print(vector)


[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
import numpy as np

# Створення двовимірного масиву (матриці) розміром 3x3, заповненого нулями
matrix = np.zeros((3, 3))

# Виведення значення матриці
print(matrix)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
import numpy as np

# Створення масиву розміром 5x5, заповненого випадковими цілими числами в діапазоні від 1 до 10
matrix = np.random.randint(1, 11, size=(5, 5))

# Виведення значення масиву
print(matrix)


[[ 8 10  2  9  3]
 [ 4  9 10  3  9]
 [ 3  1 10  6  7]
 [ 4  7  2  8 10]
 [ 6  3 10  7  5]]


In [9]:
import numpy as np

# Створення масиву розміром 4x4, заповненого випадковими дійсними числами в діапазоні від 0 до 1
matrix = np.random.random((4, 4))

# Виведення значення масиву
print(matrix)


[[0.57374273 0.83816911 0.74916217 0.44698156]
 [0.89696281 0.28694238 0.48545014 0.12970002]
 [0.60823029 0.46400965 0.71800198 0.84208207]
 [0.09568761 0.36697105 0.45285281 0.06924861]]


In [7]:
import numpy as np

# Створення двох одновимірних масивів розміром 5, заповнених випадковими цілими числами в діапазоні від 1 до 10
array1 = np.random.randint(1, 11, size=5)
array2 = np.random.randint(1, 11, size=5)

# Поелементні операції додавання, віднімання та множення
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2

# Виведення значень масивів та результатів операцій
print("Array 1:", array1)
print("Array 2:", array2)
print("Addition:", addition)
print("Subtraction:", subtraction)
print("Multiplication:", multiplication)


Array 1: [1 8 2 4 2]
Array 2: [3 1 9 7 2]
Addition: [ 4  9 11 11  4]
Subtraction: [-2  7 -7 -3  0]
Multiplication: [ 3  8 18 28  4]


In [10]:
import numpy as np

# Створення двох векторів розміром 7, заповнених довільними числами
vector1 = np.random.rand(7)
vector2 = np.random.rand(7)

# Знаходження скалярного добутку
dot_product = np.dot(vector1, vector2)

# Виведення значень векторів та скалярного добутку
print("Vector 1:", vector1)
print("Vector 2:", vector2)
print("Dot Product:", dot_product)


Vector 1: [0.30774988 0.47621161 0.06661705 0.907293   0.742245   0.57411846
 0.04524875]
Vector 2: [0.40343165 0.18472501 0.39038437 0.49409861 0.6454131  0.65518634
 0.24167658]
Dot Product: 1.5525674867523334


In [12]:
import numpy as np

# Створення матриці розміром 2x2 з випадковими цілими числами від 1 до 10
matrix1 = np.random.randint(1, 11, size=(2, 2))

# Створення матриці розміром 2x3 з випадковими цілими числами від 1 до 10
matrix2 = np.random.randint(1, 11, size=(2, 3))

# Перемноження матриць
result = np.dot(matrix1, matrix2)

print("Матриця 2x2:")
print(matrix1)
print("\nМатриця 2x3:")
print(matrix2)
print("\nРезультат множення:")
print(result)



Матриця 2x2:
[[ 1 10]
 [ 9  4]]

Матриця 2x3:
[[2 6 5]
 [1 7 4]]

Результат множення:
[[12 76 45]
 [22 82 61]]


In [13]:
import numpy as np

# Створення матриці 3x3 з випадковими цілими числами від 1 до 10
matrix = np.random.randint(1, 11, size=(3, 3))

print("Матриця 3x3:")
print(matrix)

# Перевірка, чи матриця є оберненою (детермінант не дорівнює нулю)
if np.linalg.det(matrix) != 0:
    # Знаходження оберненої матриці
    inverse_matrix = np.linalg.inv(matrix)
    print("\nОбернена матриця:")
    print(inverse_matrix)
else:
    print("\nМатриця не має оберненої матриці (детермінант дорівнює нулю).")


Матриця 3x3:
[[ 9  6  7]
 [ 3  6  6]
 [ 9 10  8]]

Обернена матриця:
[[ 0.125      -0.22916667  0.0625    ]
 [-0.3125     -0.09375     0.34375   ]
 [ 0.25        0.375      -0.375     ]]


In [14]:
import numpy as np

# Створення матриці 4x4 з випадковими дійсними числами від 0 до 1
matrix = np.random.rand(4, 4)

print("Матриця 4x4:")
print(matrix)

# Транспонування матриці
transposed_matrix = matrix.T

print("\nТранспонована матриця:")
print(transposed_matrix)


Матриця 4x4:
[[0.40391671 0.43578661 0.98288639 0.25928276]
 [0.60870369 0.63045433 0.20391809 0.77474858]
 [0.33169391 0.53858508 0.08489552 0.56828191]
 [0.30648403 0.99411414 0.72937259 0.27182406]]

Транспонована матриця:
[[0.40391671 0.60870369 0.33169391 0.30648403]
 [0.43578661 0.63045433 0.53858508 0.99411414]
 [0.98288639 0.20391809 0.08489552 0.72937259]
 [0.25928276 0.77474858 0.56828191 0.27182406]]


In [15]:
import numpy as np

# Створення матриці 3x4 з випадковими цілими числами від 1 до 10
matrix = np.random.randint(1, 11, size=(3, 4))

# Створення вектора розміром 4 з випадковими цілими числами від 1 до 10
vector = np.random.randint(1, 11, size=4)

print("Матриця 3x4:")
print(matrix)

print("\nВектор розміром 4:")
print(vector)

# Перемноження матриці на вектор
result = np.dot(matrix, vector)

print("\nРезультат множення матриці на вектор:")
print(result)


Матриця 3x4:
[[ 8  7  8  3]
 [ 1  2 10  6]
 [ 5  4  5  7]]

Вектор розміром 4:
[3 5 4 2]

Результат множення матриці на вектор:
[97 65 69]
