<a href="https://colab.research.google.com/github/OlhaYastrebova/goit-ds-hw/blob/main/Hw6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

напишіть функцію гіпотези лінійної регресії у векторному вигляді

In [ ]:
import numpy as np
import pandas as pd

def hypothesis(X, w):
    return np.dot(X, w)


створіть функцію для обчислення функції втрат у векторному вигляді

In [ ]:
def compute_cost(X, y, w):
    m = len(y)  # Кількість навчальних прикладів
    predictions = np.dot(X, w)  # Обчислення гіпотези
    errors = predictions - y  # Відхилення від реальних значень
    cost = (1 / (2 * m)) * np.dot(errors.T, errors)  # Функція втрат (середньоквадратична помилка)
    return cost

реалізуйте один крок градієнтного спуску

In [ ]:
def gradient_descent_step(X, y, w, alpha):
    m = len(y)  # Кількість навчальних прикладів

    # Обчислення передбачень моделі
    predictions = np.dot(X, w)

    # Обчислення похибок (відхилень від реальних значень)
    errors = predictions - y

    # Обчислення градієнтів
    gradient = (1 / m) * np.dot(X.T, errors)

    # Оновлення параметрів
    w = w - alpha * gradient

    return w

знайдіть найкращі параметри *w*
  для датасету використовуючи написані вами функції, прогнозуючу ціну на будинок залежно від площі, кількості ванних кімнат та кількості спалень

In [33]:
# Прочитайте CSV файл
df = pd.read_csv('/content/Housing.csv')
df


price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0    13300000  7420         4          2        3      yes        no       no   
1    12250000  8960         4          4        4      yes        no       no   
2    12250000  9960         3          2        2      yes        no      yes   
3    12215000  7500         4          2        2      yes        no      yes   
4    11410000  7420         4          1        2      yes       yes      yes   
..        ...   ...       ...        ...      ...      ...       ...      ...   
540   1820000  3000         2          1        1      yes        no      yes   
541   1767150  2400         3          1        1       no        no       no   
542   1750000  3620         2          1        1      yes        no       no   
543   1750000  2910         3          1        1       no        no       no   
544   1750000  3850         3          1        2      yes        no       no   

    hotwaterheating airconditioning  parking prefarea furnishingstatus  
0                no             yes        2      yes        furnished  
1                no             yes        3       no        furnished  
2                no              no        2      yes   semi-furnished  
3                no             yes        3      yes        furnished  
4                no             yes        2       no        furnished  
..              ...             ...      ...      ...              ...  
540              no              no        2       no      unfurnished  
541              no              no        0       no   semi-furnished  
542              no              no        0       no      unfurnished  
543              no              no        0       no        furnished  
544              no              no        0       no      unfurnished  

[545 rows x 13 columns]

In [41]:
# Вибір ознак для X
X = df[['area', 'bathrooms', 'bedrooms']].values

# Вибір цільової змінної для y
y = df['price'].values

# Додавання стовпця одиниць для w_0 (зсув)
X = np.hstack((np.ones((X.shape[0], 1)), X))

print("X:", X)
print("y:", y)

X: [[1.00e+00 7.42e+03 2.00e+00 4.00e+00]
 [1.00e+00 8.96e+03 4.00e+00 4.00e+00]
 [1.00e+00 9.96e+03 2.00e+00 3.00e+00]
 ...
 [1.00e+00 3.62e+03 1.00e+00 2.00e+00]
 [1.00e+00 2.91e+03 1.00e+00 3.00e+00]
 [1.00e+00 3.85e+03 1.00e+00 3.00e+00]]
y: [13300000 12250000 12250000 12215000 11410000 10850000 10150000 10150000
  9870000  9800000  9800000  9681000  9310000  9240000  9240000  9100000
  9100000  8960000  8890000  8855000  8750000  8680000  8645000  8645000
  8575000  8540000  8463000  8400000  8400000  8400000  8400000  8400000
  8295000  8190000  8120000  8080940  8043000  7980000  7962500  7910000
  7875000  7840000  7700000  7700000  7560000  7560000  7525000  7490000
  7455000  7420000  7420000  7420000  7350000  7350000  7350000  7350000
  7343000  7245000  7210000  7210000  7140000  7070000  7070000  7035000
  7000000  6930000  6930000  6895000  6860000  6790000  6790000  6755000
  6720000  6685000  6650000  6650000  6650000  6650000  6650000  6650000
  6629000  6615000  6615

In [52]:
# Ініціалізуємо параметри (початково всі нулі)
w = np.zeros(X.shape[1])

# Кількість ітерацій
iterations = 1000

# Коефіцієнт навчання (learning rate)
alpha = 0.01

def compute_cost(X, y, w):
    m = len(y)
    predictions = np.dot(X, w)
    cost = (1 / (2 * m)) * np.sum((predictions - y) ** 2)
    return cost

def gradient_descent(X, y, w, alpha, iterations):
    m = len(y)
    cost_history = np.zeros(iterations)

    for i in range(iterations):
        w = gradient_descent_step(X, y, w, alpha)
        cost_history[i] = compute_cost(X, y, w)

    return w, cost_history

# Нормалізація ознак
mean_X = np.mean(X[:, 1:], axis=0)
std_X = np.std(X[:, 1:], axis=0)
X[:, 1:] = (X[:, 1:] - mean_X) / std_X

# Перезапуск градієнтного спуску
optimal_w, cost_history = gradient_descent(X, y, w, alpha, iterations)

print("Оптимальні параметри w:", optimal_w)

Оптимальні параметри w: [4766523.46205873  821199.26709864  695515.99623791  300296.28560637]


знайдіть ці ж параметри за допомогою аналітичного рішення

In [46]:
# Використання аналітичного рішення для знаходження параметрів w
def normal_equation(X, y):
    return np.linalg.inv(X.T @ X) @ X.T @ y

# Знаходимо оптимальні параметри w за допомогою нормальних рівнянь
optimal_w_analytical = normal_equation(X, y)

print("Оптимальні параметри w (нормальні рівняння):", optimal_w_analytical)


Оптимальні параметри w (нормальні рівняння): [4766729.24770642  821214.14349519  695808.52272538  299983.57107963]


для перевірки спрогнозованих значень, використайте LinearRegression з бібліотеки scikit-learn та порівняйте результати

In [53]:
from sklearn.linear_model import LinearRegression

# Створення та тренування моделі LinearRegression
model = LinearRegression()
model.fit(X[:, 1:], y)  # Виключаємо перший стовпець з одиницями, бо sklearn додає його автоматично

# Отримання прогнозованих параметрів w
w_sklearn = np.hstack((model.intercept_, model.coef_))

print("Оптимальні параметри w (scikit-learn):", w_sklearn)


Оптимальні параметри w (scikit-learn): [4766729.24770642  821214.14349519  695808.52272537  299983.57107963]


In [54]:
# Прогнозування з використанням параметрів від градієнтного спуску
predictions_gd = X @ optimal_w

# Прогнозування з використанням параметрів від нормальних рівнянь
predictions_ne = X @ optimal_w_analytical

# Прогнозування з використанням scikit-learn
predictions_sklearn = model.predict(X[:, 1:])

# Виведення результатів
print("Прогнози (градієнтний спуск):", predictions_gd)
print("Прогнози (нормальні рівняння):", predictions_ne)
print("Прогнози (scikit-learn):", predictions_sklearn)


Прогнози (градієнтний спуск): [ 7036428.7494915  10390646.39452105  7591224.59703361  7066729.22087155
  5650961.9640097   8044951.88757889  8861252.36998402 12154616.38770821
  5908515.97074012  5996662.2906585   7432926.90244382  7884062.16797742
  6706911.12323346  5551705.65186907  6773111.86977227  5113128.59701382
  6725848.91784599  7038240.9943477   5561093.01457029  6250428.73846642
  4069574.57925831  6528814.31927062  5482334.05735312  5545942.77888026
  7151867.76202289  6703123.56431095  6091351.26372116  5794807.66845988
  7644413.49115879  6309217.43637031  6650016.20479082  5084640.37048997
  6074388.78317492  7461667.81351293  5838527.6652788   6470107.15597177
  6652667.49603657  7634863.05924748  4705884.47823935  6498595.38249562
  4914200.21897719  6227703.38493138  6273154.09200145  6498595.38249562
  6498595.38249562  6091351.26372116  6091351.26372116  4933138.01358972
  5447466.2468951   6636759.74856205  6636759.74856205  4828980.1432208
  6498595.38249562  57